name: dmp
channels:
  - defaults
  - pytorch
  - open3d-admin
dependencies:
  - python=3.7
  - cython
  - pytorch=1.10.0
  - cudatoolkit=11.3
  - numpy
  - matplotlib
  - tensorflow
  - tensorboard
  - open3d
  - pip
  - pip:
    - pyyaml
    - addict
    - plyfile
    - --find-links  https://pytorch-geometric.com/whl/torch-1.10.0+cu113.html
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv
    - torch-geometric
    - sklearn
    - wandb
    - pymeshlab
